# Generated by Django 4.1.2 on 2022-10-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contact_person_phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
