# Generated by Django 4.1.3 on 2023-02-24 23:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_team_picture_team_main_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="This icon should be chosen from Themify Icons. You can find all available icons <a href='https://themify.me/themify-icons' target='_blank'>here.</a> A preview can be seen below.", max_length=50, validators=[django.core.validators.RegexValidator('ti-.+', message='Please fill out a valid Themify Icon string.')])),
                ('value', models.CharField(help_text='The big number indicating this fact', max_length=10)),
                ('context', models.CharField(help_text='The context of the number', max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='teams.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
