# Generated by Django 4.1.3 on 2023-02-25 14:38

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_teamfact_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='front_page_picture',
            field=models.ImageField(default="", help_text='This image is used to create the hexagon on the main page. THIS PICTURE HAS TO BE SQUARE.', upload_to='teams'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='banner_picture',
            field=models.ImageField(help_text="This picture will serve as the background on your team's page.", upload_to='teams'),
        ),
        migrations.AlterField(
            model_name='team',
            name='main_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text="In most cases this would be your teams color. It is used to color the headers and icons on your team's page.", image_field=None, max_length=18, samples=None),
        ),
    ]
