# Generated by Django 4.1.3 on 2023-03-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_alter_team_logo_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtextsection',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
