# Generated by Django 4.2.5 on 2023-09-05 21:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_alter_teamtextsection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='main_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text="In most cases this would be your teams color. It is used to color the headers and icons on your team's page.", image_field=None, max_length=25, samples=None),
        ),
    ]
