# Generated by Django 4.1.3 on 2023-02-24 22:05

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news_articles', '0007_newsarticle_delete_event')
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='This will be the title of this event', max_length=100)),
                ('summary', models.CharField(help_text='This will be the text that is displayed on the front page, together with the event', max_length=250)),
                ('description', django_quill.fields.QuillField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events')),
                ('date', models.DateTimeField(help_text='When does this event take place?')),
                ('location', models.CharField(help_text='Where does this event take place?', max_length=100)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
