# Generated by Django 4.1.2 on 2022-10-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events', blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
