# Generated by Django 4.1.3 on 2023-04-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_switch_to_start_and_end_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entire_day',
            field=models.BooleanField(blank=True, help_text='Does this event last the entire day?', null=True, verbose_name='Lasts the entire day'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(help_text='When does this event end?', verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(help_text='When does this event start?', verbose_name='Start time'),
        ),
    ]
