# Generated by Django 4.1.3 on 2023-04-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_entire_day_alter_event_end_alter_event_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='entire_day',
            field=models.BooleanField(default=False, help_text='Does this event last the entire day?', verbose_name='Lasts the entire day'),
            preserve_default=False,
        ),
    ]
