# Generated by Django 4.1.3 on 2022-12-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_short_description_event_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
    ]
