# Generated by Django 4.1.3 on 2023-03-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0008_alter_teamfact_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sender', models.EmailField(help_text='The email from the person that sent this mail.', max_length=254, verbose_name='From')),
                ('message', models.CharField(help_text='The original message as send by the messenger.', max_length=500)),
                ('read', models.BooleanField(default=False, help_text='Whether this email is already read by someone.')),
                ('recipient', models.ForeignKey(blank=True, help_text='For which team is this email meant?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='teams.team', verbose_name='To')),
            ],
        ),
    ]
