# Generated by Django 4.1.3 on 2023-03-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_presspictures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PressPictures',
            new_name='PressPicture',
        ),
    ]
