# Generated by Django 4.1.3 on 2023-03-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_rename_presspictures_presspicture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presspicture',
            options={'verbose_name': 'press picture', 'verbose_name_plural': 'press pictures'},
        ),
    ]
