# Generated by Django 4.1.3 on 2023-03-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_alter_presspicture_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='time_send',
            field=models.DateTimeField(auto_now=True, help_text='When was this email send?'),
        ),
    ]
