# Generated by Django 4.1.3 on 2023-04-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_email_time_send'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
