# Generated by Django 4.1.3 on 2022-12-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Warning! This field allows for the use of HTML tags. Be cautious since there are no checks in place. ALWAYS check the page immediately after creation.'),
        ),
    ]
