# Generated by Django 4.1.3 on 2022-12-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0004_alter_event_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='summary',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='This will be the title of the news article', max_length=100),
        ),
        migrations.RenameField(
            model_name='event',
            old_name='short_description',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.CharField(help_text='Shown as a side text on the frontpage and news page', max_length=250),
        ),
        migrations.RenameField(
            model_name='event',
            old_name='creation_date',
            new_name='event_date',
        )
    ]
