# Generated by Django 4.1.3 on 2023-02-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0006_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_articles'),
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RenameModel('Event', 'NewsArticle'),
    ]
