# Generated by Django 4.1.3 on 2023-02-24 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0007_newsarticle_delete_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'verbose_name': 'news article', 'verbose_name_plural': 'news articles'},
        ),
    ]
