# Generated by Django 4.1.3 on 2023-05-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0009_remove_newsarticle_description_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='news_articles.newsarticle'),
        ),
    ]
